### PR TITLE
bump the Nump package to 0.96.0

### PR DESCRIPTION
**Pull request by amtoine**
followup to:
- https://github.com/FMotalleb/nu_plugin_clipboard/pull/11

i forgot to bump the Nupm package... wasn't well focused this morning :rofl: :sob:

## Summary by CodeRabbit

- **New Features**
	- Updated the clipboard plugin to version 0.96.0, which may include enhancements and bug fixes.
  
- **Bug Fixes**
	- Potential resolutions or improvements included in the new plugin version.

### CODE REVIEW

**Comment by amtoine** [comment]
really sorry for the double PR

**Comment by fmotalleb** [comment]
NP. Tnx anyway

**Comment by fmotalleb** [comment]
I was just commiting the `nupm.nuon` file and boom, power outage

**Comment by amtoine** [comment]
> I was just commiting the `nupm.nuon` file and boom, power outage
>
that sounds not fun :rofl:

**Comment by amtoine** [comment]
added to Nupm in https://github.com/nushell/nupm/pull/94 :ok_hand:

**Pull request merged**
